------------------------------ MODULE QuestionMarketLMSR ------------------------------
(* Auto-generated by scripts/generate_lmsr_tla.py — re-run script after edits, do not hand-edit.
   Matches lmsr_math_avm.py structure (Taylor loops, BUY margin, ln Newton x4, no early break).
   CONSTANTS: LMSR_SCALE, LN2_FP, EXP_TAYLOR_TERMS, LN_TAYLOR_TERMS,
   BUY_APPROXIMATION_MARGIN, Outcomes (finite non-empty). *)
EXTENDS Integers, TLC

CONSTANTS
    LMSR_SCALE,
    LN2_FP,
    EXP_TAYLOR_TERMS,
    LN_TAYLOR_TERMS,
    BUY_APPROXIMATION_MARGIN,
    Outcomes

ASSUME
    /\ LMSR_SCALE > 0
    /\ EXP_TAYLOR_TERMS > 1
    /\ LN_TAYLOR_TERMS > 1
    /\ BUY_APPROXIMATION_MARGIN >= 0
    /\ Outcomes # {}

(* Numeric max outcome — receives LMSR_SCALE - sum(others) as in lmsr_prices. *)
LastOutcome == CHOOSE lo \in Outcomes : \A o \in Outcomes : o <= lo

OtherOutcomes == Outcomes \ {LastOutcome}

LmsrMax2(a, b) == IF a >= b THEN a ELSE b

FloorDiv(n, d) == IF d = 0 THEN 0 ELSE n \div d

CeilDiv(n, d) ==
    IF d = 0 THEN 0 ELSE IF (n % d) = 0 THEN n \div d ELSE (n \div d) + 1

MulDivFloor(a, b, denom) == FloorDiv(a * b, denom)

MulDivCeil(a, b, denom) == CeilDiv(a * b, denom)

RECURSIVE ExpTaylorPosReduced(_, _, _, _)
ExpTaylorPosReduced(step, total, term, xFp) ==
    IF step >= (EXP_TAYLOR_TERMS - 1)
    THEN total
    ELSE LET k == step + 1
             newTerm == FloorDiv(term * xFp, k * LMSR_SCALE)
         IN ExpTaylorPosReduced(step + 1, total + newTerm, newTerm, xFp)

RECURSIVE ExpTaylorNegReduced(_, _, _, _)
ExpTaylorNegReduced(step, total, termAbs, deltaFp) ==
    IF step >= (EXP_TAYLOR_TERMS - 1)
    THEN total
    ELSE LET k == step + 1
             newAbs == FloorDiv(termAbs * deltaFp, k * LMSR_SCALE)
             newTotal ==
                 IF newAbs = 0
                 THEN total
                 ELSE IF (k % 2) = 1
                      THEN IF total >= newAbs THEN total - newAbs ELSE 0
                      ELSE total + newAbs
         IN ExpTaylorNegReduced(step + 1, newTotal, newAbs, deltaFp)

RECURSIVE ExpSquareRepeat(_, _)
ExpSquareRepeat(acc, hLeft) ==
    IF hLeft = 0 THEN acc ELSE ExpSquareRepeat(FloorDiv(acc * acc, LMSR_SCALE), hLeft - 1)

RECURSIVE ExpHalveWhile(_, _, _)
ExpHalveWhile(reduced, halvings, xFp) ==
    IF reduced <= LMSR_SCALE
    THEN LET base == ExpTaylorPosReduced(0, LMSR_SCALE, LMSR_SCALE, reduced)
         IN ExpSquareRepeat(base, halvings)
    ELSE ExpHalveWhile(FloorDiv(reduced, 2), halvings + 1, xFp)

ExpPosFp(xFp) == IF xFp = 0 THEN LMSR_SCALE ELSE ExpHalveWhile(xFp, 0, xFp)

RECURSIVE ExpNegHalveWhile(_, _, _)
ExpNegHalveWhile(reduced, halvings, deltaFp) ==
    IF reduced <= LMSR_SCALE
    THEN LET base == ExpTaylorNegReduced(0, LMSR_SCALE, LMSR_SCALE, reduced)
         IN ExpSquareRepeat(base, halvings)
    ELSE ExpNegHalveWhile(FloorDiv(reduced, 2), halvings + 1, deltaFp)

ExpNegFp(deltaFp) == IF deltaFp = 0 THEN LMSR_SCALE ELSE ExpNegHalveWhile(deltaFp, 0, deltaFp)

RECURSIVE LnReduceY(_, _)
LnReduceY(yFp, powerTwo) ==
    IF yFp < (2 * LMSR_SCALE)
    THEN <<yFp, powerTwo>>
    ELSE LnReduceY(CeilDiv(yFp, 2), powerTwo + 1)

RECURSIVE LnTaylorSeries(_, _, _, _)
LnTaylorSeries(step, seriesFp, oddPowerFp, zSqFp) ==
    IF step >= (LN_TAYLOR_TERMS - 1)
    THEN seriesFp
    ELSE LET k == step + 1
             newOdd == FloorDiv(oddPowerFp * zSqFp, LMSR_SCALE)
             denom == (k * 2) + 1
             newSeries == seriesFp + FloorDiv(newOdd, denom)
         IN LnTaylorSeries(step + 1, newSeries, newOdd, zSqFp)

LnFpAfterTaylor(xFp) ==
    LET pr == LnReduceY(xFp, 0)
        yFp == pr[1]
        powerTwo == pr[2]
        zNum == (yFp - LMSR_SCALE) * LMSR_SCALE
        zDen == yFp + LMSR_SCALE
        zFp == FloorDiv(zNum, zDen)
        zSqFp == FloorDiv(zFp * zFp, LMSR_SCALE)
        seriesFp == LnTaylorSeries(0, zFp, zFp, zSqFp)
    IN (seriesFp * 2) + (powerTwo * LN2_FP)

NewtonLnStep(xFp, r) ==
    LET est == ExpPosFp(r)
        ratioFp == IF est = 0 THEN LMSR_SCALE ELSE FloorDiv(xFp * LMSR_SCALE, est)
    IN IF ratioFp > LMSR_SCALE
       THEN r + (ratioFp - LMSR_SCALE)
       ELSE IF ratioFp < LMSR_SCALE
            THEN r - (LMSR_SCALE - ratioFp)
            ELSE r

LnFp(xFp) ==
    IF xFp < LMSR_SCALE
    THEN 0
    ELSE IF xFp = LMSR_SCALE
         THEN 0
         ELSE LET r0 == LnFpAfterTaylor(xFp)
                  r1 == NewtonLnStep(xFp, r0)
                  r2 == NewtonLnStep(xFp, r1)
                  r3 == NewtonLnStep(xFp, r2)
                  r4 == NewtonLnStep(xFp, r3)
              IN r4

ExponentFp(q_i, b) == FloorDiv(q_i * LMSR_SCALE, b)

RECURSIVE MaxExponentFpRec(_, _, _)
MaxExponentFpRec(q, b, os) ==
    IF os = {}
    THEN 0
    ELSE LET o == CHOOSE x \in os : TRUE
         IN LmsrMax2(ExponentFp(q[o], b), MaxExponentFpRec(q, b, os \ {o}))

MaxExponentFp(q, b) == MaxExponentFpRec(q, b, Outcomes)

RECURSIVE SumShiftedExpRec(_, _, _, _)
SumShiftedExpRec(q, b, sharedMax, os) ==
    IF os = {}
    THEN 0
    ELSE LET o == CHOOSE x \in os : TRUE
             e == ExponentFp(q[o], b)
         IN ExpNegFp(sharedMax - e) + SumShiftedExpRec(q, b, sharedMax, os \ {o})

SumShiftedExpFp(q, b, sharedMax) == SumShiftedExpRec(q, b, sharedMax, Outcomes)

LogSumExpFp(q, b) ==
    LET maxE == MaxExponentFp(q, b)
        s == SumShiftedExpFp(q, b, maxE)
    IN maxE + LnFp(s)

LmsrCostFloor(q, b) == MulDivFloor(b, LogSumExpFp(q, b), LMSR_SCALE)

LmsrCostCeil(q, b) == MulDivCeil(b, LogSumExpFp(q, b), LMSR_SCALE)

QAfterBuy(q, outcome, shares) == [o \in Outcomes |-> IF o = outcome THEN q[o] + shares ELSE q[o]]

QAfterSell(q, outcome, shares) == [o \in Outcomes |-> IF o = outcome THEN q[o] - shares ELSE q[o]]

LmsrCostDelta(q, b, outcome, shares) ==
    LET qAfter == QAfterBuy(q, outcome, shares)
        costBeforeFloor == LmsrCostFloor(q, b)
        costAfterCeil == LmsrCostCeil(qAfter, b)
        costAfterFloor == LmsrCostFloor(qAfter, b)
        directQuote == IF costAfterCeil > costBeforeFloor THEN costAfterCeil - costBeforeFloor ELSE 0
        roundTripFloor == IF costAfterFloor > costBeforeFloor THEN costAfterFloor - costBeforeFloor ELSE 0
        paddedDirect == IF shares > 0 THEN directQuote + BUY_APPROXIMATION_MARGIN ELSE directQuote
        maxBefore == MaxExponentFp(q, b)
        maxAfter == MaxExponentFp(qAfter, b)
        sharedMax == LmsrMax2(maxBefore, maxAfter)
        sumBefore == SumShiftedExpFp(q, b, sharedMax)
        sumAfter == SumShiftedExpFp(qAfter, b, sharedMax)
        ratioFp == IF sumBefore > 0 THEN MulDivCeil(sumAfter * LMSR_SCALE, sumBefore, LMSR_SCALE) ELSE LMSR_SCALE
        ratioQuote == IF sumBefore > 0 THEN MulDivCeil(b, LnFp(ratioFp), LMSR_SCALE) ELSE directQuote
        ratioCap == ratioQuote + BUY_APPROXIMATION_MARGIN
        paddedCapped == IF paddedDirect > ratioCap THEN ratioCap ELSE paddedDirect
    IN LmsrMax2(LmsrMax2(ratioQuote, paddedCapped), roundTripFloor)

LmsrSellReturn(q, b, outcome, shares) ==
    LET qAfter == QAfterSell(q, outcome, shares)
        maxBefore == MaxExponentFp(q, b)
        maxAfter == MaxExponentFp(qAfter, b)
        sharedMax == LmsrMax2(maxBefore, maxAfter)
        sumBefore == SumShiftedExpFp(q, b, sharedMax)
        sumAfter == SumShiftedExpFp(qAfter, b, sharedMax)
        ratioFp == MulDivFloor(sumBefore * LMSR_SCALE, sumAfter, LMSR_SCALE)
    IN MulDivFloor(b, LnFp(ratioFp), LMSR_SCALE)

PriceAt(q, b, sharedMax, sumExp, o) ==
    LET e == ExponentFp(q[o], b)
        w == ExpNegFp(sharedMax - e)
    IN MulDivFloor(w, LMSR_SCALE, sumExp)

RECURSIVE SumPriceOthers(_, _, _, _, _)
SumPriceOthers(q, b, sharedMax, sumExp, os) ==
    IF os = {}
    THEN 0
    ELSE LET o == CHOOSE x \in os : TRUE
         IN PriceAt(q, b, sharedMax, sumExp, o) + SumPriceOthers(q, b, sharedMax, sumExp, os \ {o})

LmsrPrices(q, b) ==
    LET sharedMax == MaxExponentFp(q, b)
        sumExp == SumShiftedExpFp(q, b, sharedMax)
        sumOthers == SumPriceOthers(q, b, sharedMax, sumExp, OtherOutcomes)
    IN [o \in Outcomes |-> IF o = LastOutcome THEN LMSR_SCALE - sumOthers ELSE PriceAt(q, b, sharedMax, sumExp, o)]

RECURSIVE LmsrMaxPriceRec(_, _)
LmsrMaxPriceRec(p, os) ==
    IF os = {}
    THEN 0
    ELSE LET o == CHOOSE x \in os : TRUE
         IN LmsrMax2(p[o], LmsrMaxPriceRec(p, os \ {o}))

LmsrMaxPrice(q, b) == LET p == LmsrPrices(q, b) IN LmsrMaxPriceRec(p, Outcomes)

RECURSIVE LmsrGaugeAlphaRec(_, _)
LmsrGaugeAlphaRec(prices, os) ==
    IF os = {}
    THEN 0
    ELSE LET o == CHOOSE x \in os : TRUE
             invP == MulDivCeil(LMSR_SCALE * LMSR_SCALE, prices[o], LMSR_SCALE)
             lnInv == LnFp(invP)
         IN LmsrMax2(lnInv, LmsrGaugeAlphaRec(prices, os \ {o}))

LmsrGaugeAlphaFromPrices(prices) == LmsrGaugeAlphaRec(prices, Outcomes)

LmsrCollateralRequiredFromPrices(targetDeltaB, prices) ==
    MulDivCeil(targetDeltaB, LmsrGaugeAlphaFromPrices(prices), LMSR_SCALE)

LmsrNormalizedQFromPrices(prices, newB) ==
    LET alpha == LmsrGaugeAlphaFromPrices(prices)
    IN [o \in Outcomes |->
            LET invP == MulDivCeil(LMSR_SCALE * LMSR_SCALE, prices[o], LMSR_SCALE)
                lnInv == LnFp(invP)
            IN IF alpha >= lnInv THEN MulDivFloor(newB * (alpha - lnInv), LMSR_SCALE, LMSR_SCALE) ELSE 0]

LmsrLiquidityScaleB(b, deposit, pool) == MulDivFloor(b, pool + deposit, pool)

LmsrLiquidityScaleQ(q, deposit, pool) ==
    [o \in Outcomes |-> MulDivFloor(q[o] * (pool + deposit), pool, pool)]

RECURSIVE PriceSumRec(_, _)
PriceSumRec(prices, os) ==
    IF os = {} THEN 0 ELSE LET o == CHOOSE x \in os : TRUE IN prices[o] + PriceSumRec(prices, os \ {o})

PriceSum(prices) == PriceSumRec(prices, Outcomes)

PricesValid(prices) ==
    /\ \A o \in Outcomes : prices[o] > 0
    /\ PriceSum(prices) = LMSR_SCALE

=============================================================================
